assume role
Run echo "BEGIN: Nuke"
BEGIN: Nuke
***
    "Credentials": ***
        "AccessKeyId": "ASIAVCIM4KSOY2X4CI6H",
        "SecretAccessKey": "slSCPfhfLMUSX0oVeAd2cB9xVPpHkCB9GJPkhiOK",
        "SessionToken": "IQoJb3JpZ2luX2VjELL//////////wEaCWV1LXdlc3QtMiJHMEUCIHX1Y5683y5DuJYkT31rihg/VDWuxMHxUWdJ9EwZ1mMVAiEA8AKtk1IvSl8SY7YeBVnXzk3z1/i5QH5EYoySSvjtsugqqAIIWxABGgwzNDg0NTYyNDQzODEiDBd6IvCvCpdbnjuy6CqFAjdkdzwQM6VjLMV+k+i2F7trVOq5Pi4d51ZD7hZzv1whxJEyqTuXGttm6xHKYEPgBXc+5HbOXM1TGT/AGNNDJ/GFCa28W0IFK5pOMY3aCwu7uBKdXNEYmZVSeX8OoltLOVWWgkUYboWOPqBpKx1tA4QIABRzGtX2KA73vb16CdiR9XFaUT16buOBn3PA6w4GTZa2923ckqBqumndo+NKghxQqpvZaSn8dXyXde7PJqVKA8Sc57q/QnFJ0MEvGhQg3nKzY+NykJ6fUQEeWgAo0CMPpyB9iUTpnTWGz0ufq3wCo2b7RtQWyRwFNGHRHo5x9Kub5m5fmWtH4YeSDAJeylG+NmuPvzCYt9qSBjqdAfiWw2DdNU/mesEvpHlidKrAW4gkoaejU8BJtHEdNXODc0PbrSAWVsFN90iz5FMYdww8bbDJI0GCfUZXsp7y7uMXYkwl+5xDfd+tOWsy4Hv+noU8pRTz1k4kmJERLHWHB50OmjF7JsK3JDL1hiWBMZsJhdoFh3yOwtubcAh6EY9P5np7PVZ9kahWiDryla0WUZ34sDSm3KdsA7fU5yQ=",
        "Expiration": "2022-04-13T10:44:56+00:00"
    ***,
    "AssumedRoleUser": ***
        "AssumedRoleId": "AROAVCIM4KSOX2S2YKKGP:SPRINKLER_DEVELOPMENT_ACCID",
        "Arn": "arn:aws:sts::348456244381:assumed-role/MemberInfrastructureAccess/SPRINKLER_DEVELOPMENT_ACCID"
    ***
***
Error: failed get account alias: AccessDenied: User: arn:aws:iam::946070829339:user/member-ci is not authorized to perform: iam:ListAccountAliases on resource: *
	status code: 403, request id: 1aadda73-e1bd-4998-8b14-db3340243806
Error: Process completed with exit code 255.