Error: Error putting S3 policy: MalformedPolicy: Invalid principal in… (#590)
* Error: Error putting S3 policy: MalformedPolicy: Invalid principal in policy
	status code: 400, request id: T26PNSZK2ZDM5DFK, host id: JuoOiev7oL0/GqazjUmy8YdyWUGlJsVHO2I5fmMFkNcGriW/NZ5UeF+qimEHBjqLnGxeD/qyDKo=

  with aws_s3_bucket_policy.allow_access_from_another_account[0],
  on s3-ukcloud-replica.tf line 56, in resource "aws_s3_bucket_policy" "allow_access_from_another_account":
  56: resource "aws_s3_bucket_policy" "allow_access_from_another_account" {

Error: error creating IAM Policy read_list_s3_access_policy: MalformedPolicyDocument: Resource s3-bucket-ukcloud-replica20220511075839843300000001 must be in ARN format or "*".
	status code: 400, request id: 14a4062d-249a-4696-b179-81160074157c

  with aws_iam_policy.read_list_s3_access_policy[0],
  on s3-ukcloud-replica.tf line 83, in resource "aws_iam_policy" "read_list_s3_access_policy":
  83: resource "aws_iam_policy" "read_list_s3_access_policy" {

* Error: Error putting S3 policy: InvalidARNError: invalid ARN
caused by: invalid Amazon s3 ARN, unknown resource type, arn:aws:s3:::s3-bucket-ukcloud-replica20220511075839843300000001

  with aws_s3_bucket_policy.allow_access_from_another_account[0],
  on s3-ukcloud-replica.tf line 56, in resource "aws_s3_bucket_policy" "allow_access_from_another_account":
  56: resource "aws_s3_bucket_policy" "allow_access_from_another_account" {

              + Version   = "2012-10-17"
            }
        )
    }

* Error: Error putting S3 policy: MalformedPolicy: Invalid principal in policy
	status code: 400, request id: WECKP97NJ4G05BW0, host id: ZBeMrZU5vGLPRDVhB6skWWxT1Wxu/1Mg8sFT+mxitaBe6fvNlHvkb9wr90eDLGZcE5o6PofrHCE=

  with aws_s3_bucket_policy.allow_access_from_another_account[0],
  on s3-ukcloud-replica.tf line 56, in resource "aws_s3_bucket_policy" "allow_access_from_another_account":
  56: resource "aws_s3_bucket_policy" "allow_access_from_another_account" {

        # (4 unchanged attributes hidden)
    }

Co-authored-by: Zuri Guardiola <37803183+zuriguardiola@users.noreply.github.com>