Can't use local variable at that point as tf fails with null value
Error: Invalid template interpolation value
│
│   on locals_preproduction.tf line 218, in locals:
│  218:               "arn:aws:secretsmanager:*:*:secret:/postgres/database/${local.arns_integration.database_hostname}/*",
│     ├────────────────
│     │ local.arns_integration.database_hostname is null
│
│ The expression result is null. Cannot include a null value in a string
│ template.