Remove sys.module override which isn't necessary in sqlalchemy>2.0 (#10422)
* Remove sys.module override which isn't necessary in sqlalchemy>2.0

This is to work around the following error:
Runtime.ImportModuleError: Unable to import module 'main': cannot import name 'base_impl' from partially initialized module 'oracledb' (most likely due to a circular import) (/var/task/oracledb/__init__.py)

* Add arbitrary change to dms folder to work around bug in cicd